apiVersion: v1
kind: Service
metadata:
  name: gitea-service
spec:
  selector:
    app: gitea-service
  ports:
    - name: gitea-http
      port: 3000
      targetPort: 3000
      nodePort: 30000
    - name: gitea-ssh
      port: 2222
      targetPort: 2222
      nodePort: 32222
  type: NodePort
